# This workflow will check flake style
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Graph Generating

on:
  push:

jobs:
  doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]

    services:
      plantuml:
        image: plantuml/plantuml-server
        ports:
          - 18080:8080

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:inkscape.dev/stable
          sudo apt-get update -y
          sudo apt-get install -y make wget curl cloc graphviz librsvg2-bin inkscape
          pip install plantumlcli
          dot -V
          plantumlcli -v
          rsvg-convert -v
          inkscape -V
      - name: Generate
        env:
          ENV_PROD: 'true'
          PLANTUML_HOST: http://localhost:18080
        run: |
          cloc .
          plantumlcli -c
          make build
          ls -al *.pdf *.svg *.png
